codecov:
  require_ci_to_pass: yes

coverage:
  range: "80...100"

  status:
    project:
      default: false  # disable the default status that measures entire project
      amiddy:
        paths:
          - /packages/amiddy
      babel-plugin-auto-logger:
        paths:
          - /packages/babel-plugin-auto-logger
